# Generated by Django 6.0.4 on 2026-04-08 01:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "trace_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "eval_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status"], name="core_run_status_b9a383_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("correctness_score", models.IntegerField()),
                ("helpfulness_score", models.IntegerField()),
                (
                    "aggregate_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("reasoning", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trace_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="core.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Span",
            fields=[
                (
                    "span_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("parent_span_id", models.UUIDField(blank=True, null=True)),
                (
                    "span_type",
                    models.CharField(
                        choices=[("llm", "llm"), ("tool", "tool"), ("chain", "chain")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status_code",
                    models.CharField(
                        choices=[("OK", "OK"), ("ERROR", "ERROR")], max_length=10
                    ),
                ),
                ("attributes", models.JSONField(default=dict)),
                (
                    "trace_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spans",
                        to="core.run",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trace_id"], name="core_span_trace_i_0a5337_idx"
                    )
                ],
            },
        ),
    ]
