# Generated by Django 6.0.4 on 2026-04-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_idempotencykey_evaluation_prompt_version_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="span",
            name="span_end_after_start",
        ),
        migrations.AddConstraint(
            model_name="span",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gte", models.F("start_time"))),
                name="span_end_after_start",
            ),
        ),
    ]
